// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS9UhubBGNZKnhJZvGAPk7lYw6SmGa3hU',
    appId: '1:545868656528:web:6eb5f5adbaad39c636cd15',
    messagingSenderId: '545868656528',
    projectId: 'afk-pub',
    authDomain: 'afk-pub.firebaseapp.com',
    storageBucket: 'afk-pub.firebasestorage.app',
    measurementId: 'G-01FTE7YK3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU0RCBsfLenDmdrH6wNTKV71wBccDzXa8',
    appId: '1:545868656528:android:f60ec86c2b880fa836cd15',
    messagingSenderId: '545868656528',
    projectId: 'afk-pub',
    storageBucket: 'afk-pub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDoiCG-jEFG3sL6cmjRTcxfVTovjivZE8',
    appId: '1:545868656528:ios:55cb5657290a90af36cd15',
    messagingSenderId: '545868656528',
    projectId: 'afk-pub',
    storageBucket: 'afk-pub.firebasestorage.app',
    iosBundleId: 'com.afk.pubadmin.pubAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDoiCG-jEFG3sL6cmjRTcxfVTovjivZE8',
    appId: '1:545868656528:ios:55cb5657290a90af36cd15',
    messagingSenderId: '545868656528',
    projectId: 'afk-pub',
    storageBucket: 'afk-pub.firebasestorage.app',
    iosBundleId: 'com.afk.pubadmin.pubAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS9UhubBGNZKnhJZvGAPk7lYw6SmGa3hU',
    appId: '1:545868656528:web:07d3fc631d39528436cd15',
    messagingSenderId: '545868656528',
    projectId: 'afk-pub',
    authDomain: 'afk-pub.firebaseapp.com',
    storageBucket: 'afk-pub.firebasestorage.app',
    measurementId: 'G-NQXZC1ETC9',
  );
}
